<a href="https://colab.research.google.com/github/Karelptrp/source-code-smt2/blob/main/matkul%20pak%20bisrul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class mahasiswa:
  #variabel class
  mata_kuliah = "Pemrograman untuk analisis data"

  def __init__(self,nama):
    #variabel instance
    self.nama = nama

  def sapa (self):
    print(f"Halo, nama saya {self.nama}, Sedang belajar {self.mata_kuliah}")

mhs1 = mahasiswa("Dimas")
mhs2 = mahasiswa("Budi")

mhs1.sapa()

print(mhs1.nama, mhs1.mata_kuliah)
print(mhs2.nama, mhs2.mata_kuliah)

Halo, nama saya Dimas, Sedang belajar Pemrograman untuk analisis data
Dimas Pemrograman untuk analisis data
Budi Pemrograman untuk analisis data


In [ ]:
class mobil:
  #variabel class
  ini_mobil = "roda 4"

  def __init__(self,nama, spesifikasi):
    #variabel instance
    self.nama = nama
    self.spesifikasi = spesifikasi

  def sapa (self):
    print(f"Mobil {self.nama}, Spesifikasi \n  {self.spesifikasi}")

mbl1 = mobil("Avanza", "Jenis Bahan Bakar: Bensin\n  Kapasitas mesin: 1329 cc\n  Tenaga: 97 hp\n  Torsi: 122 Nm\n  RPM At Max Power: 6000 RPM\n  RPM At Max TorqueL: 4200 RPM")
mbl2 = mobil("Serena", "Jenis Bahan Bakar: Bensin\n  Kapasitas mesin: 1997 cc\n  Tenaga: 147 hp\n  Torsi: 210 Nm\n  RPM At Max Power: 6000 RPM\n  RPM At Max TorqueL: 4400 RPM")

mbl1.sapa()
mbl2.sapa()

Mobil Avanza, Spesifikasi 
  Jenis Bahan Bakar: Bensin
  Kapasitas mesin: 1329 cc
  Tenaga: 97 hp
  Torsi: 122 Nm
  RPM At Max Power: 6000 RPM
  RPM At Max TorqueL: 4200 RPM
Mobil Serena, Spesifikasi 
  Jenis Bahan Bakar: Bensin
  Kapasitas mesin: 1997 cc
  Tenaga: 147 hp
  Torsi: 210 Nm
  RPM At Max Power: 6000 RPM
  RPM At Max TorqueL: 4400 RPM


In [ ]:
class mobil:
  #variabel class
  roda = "memiliki roda 4"

  def __init__(self,jenis):
    #variabel instansi
    self.jenis = jenis


mbl1 = mobil("Avanza")
mbl2 = mobil("Xemia")

print(mbl1.jenis, mobil.roda)
print(mbl2.jenis, mobil.roda)

Avanza memiliki roda 4
Xemia memiliki roda 4


In [ ]:
class Node:
  def __init__(self, data, next):
    self.data1 = data
    self.next = None

  def prepend(self, data):
    new_node = Node(data)
    new_node.next = self.head
    self.head = new_node

  def print_list(self):
    cur = self.head
    while cur:
      print(cur,data, end=" => ")
      cur = cur.next


In [ ]:
class Node():
  def __init__(self, data):
    self.data1 = data
    self.next = None

class LinkedList():
  def __init__(self):
    self.head = None

  def is_empty(self):
    return self.head is None

  def tambah_di_awal(self, data):
    new_node = Node(data)
    new_node.next = self.head
    self.head = new_node

  def __iter__(self):
    node = self.head
    while node is not None:
      yield node
      node = node.next

  def tambah_di_akhir(self, data):
    new_node = Node(data)
    if self.head is None:
      self.head = new_node
    else:
      current_node = self.head
      while current_node.next is not None:
        current_node = current_node.next
      current_node.next = new_node

  def tampilkan_kereta(self):
    current_node = self.head
    while current_node is not None:
      print(current_node.data1, end=" => ")
      current_node = current_node.next
    print("None")

kereta = LinkedList()
kereta.tambah_di_awal("Gerbong A")
kereta.tambah_di_awal("Gerbong B")
kereta.tambah_di_awal("Gerbong C")
kereta.tambah_di_akhir("Gerbong akhir")
kereta.tampilkan_kereta()

Gerbong C => Gerbong B => Gerbong A => None


Tugas Tambah di akhir

In [ ]:
class Dataset:
  def __init__(self, name):
    self.name = name

class CSVDataset(Dataset):
  def __init__(self, name, rows):
    super().__init__(name)
    self.rows = rows

In [ ]:
my_cat = Kucing("Cecep Kopling", "Berbulu putih dan suka bermain benang", "3 tahun")

print(f"Nama Kucing: {my_cat.name}")
print(f"Ciri-ciri Kucing: {my_cat.warna_bulu}")

Nama Kucing: Cecep Kopling
Ciri-ciri Kucing: Berbulu putih dan suka bermain benang


In [ ]:
class Hewan:
  def __init__(self, name):
    self.name = name

class Kucing(Hewan):
  def __init__(self, name, rows):
    super().__init__(name)
    self.rows = rows

In [ ]:
class Hewan:
  def __init__(self, name):
    self.name = name

  def makan(self):
    print(f"{self.name} sedang makan segalanya")

class Kucing(Hewan):
  def __init__(self, name, warna_bulu, umur):
    super().__init__(name)
    self.warna_bulu = warna_bulu
    self.__umur = umur

  def makan(self):
    print(f"{self.name} berbulu {self.warna_bulu} sedang makan ikan dan sekarang berumur {self.__umur}")

  def getter (self):
    return self.__umur

  def setter (self, umur_baru):
    if umur_baru > 0:
      self.__umur = umur_baru
      print("umur berhasil ditambahkan")
    else:
      print("umur harus lebih dari 0")

hewan_kaki = Hewan("Hewan Kaki 4")
hewan_kaki.makan()

#objek children
hewan_kucing = Kucing("Kucing", "Calico", "32 Months")
hewan_kucing.makan()
hewan_kucing.setter(2)

Hewan Kaki 4 sedang makan segalanya
Kucing berbulu Calico sedang makan ikan dan sekarang berumur 32 Months
umur berhasil ditambahkan


In [ ]:
list_kalimat = []
list_kalimat.append("Nama")
list_kalimat.append("Saya")
list_kalimat.append("a")
print(list_kalimat)
list_kalimat.pop()
print(list_kalimat)
list_kalimat.append("b")
print(list_kalimat)
list_kalimat.pop()
print(list_kalimat)
list_kalimat.append("aaaa")
print(list_kalimat)

['Nama', 'Saya', 'a']
['Nama', 'Saya']
['Nama', 'Saya', 'b']
['Nama', 'Saya']
['Nama', 'Saya', 'aaaa']


You can use `append()` to 'push' elements onto a list, which adds them to the end of the list. This is the standard way to add elements to a list, especially when treating it like a stack (Last-In, First-Out).

In [ ]:
my_stack = []
print(f"Initial stack: {my_stack}")

# Push elements using append()
my_stack.append("item1") # Push 'item1'
print(f"After pushing 'item1': {my_stack}")

my_stack.append("item2") # Push 'item2'
print(f"After pushing 'item2': {my_stack}")

my_stack.append("item3") # Push 'item3'
print(f"After pushing 'item3': {my_stack}")

# To 'pop' (remove the last item), you would use pop()
popped_item = my_stack.pop()
print(f"Popped item: {popped_item}, Stack after pop: {my_stack}")

popped_item = my_stack.pop()
print(f"Popped item: {popped_item}, Stack after pop: {my_stack}")

Initial stack: []
After pushing 'item1': ['item1']
After pushing 'item2': ['item1', 'item2']
After pushing 'item3': ['item1', 'item2', 'item3']
Popped item: item3, Stack after pop: ['item1', 'item2']
Popped item: item2, Stack after pop: ['item1']


In [ ]:
import numpy as np

In [ ]:
data_list=[]
data_array= np.array([0])

print(data_list)
print(data_array)

[]
[0]


In [ ]:
matrix = np.zeros((10000, 10000000))
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(7,27,2)

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [ ]:
my_traditional_list = []

for i in range(2, 11, 2):
  my_traditional_list.append(i)

print("Traditional Python list created with for loop:", my_traditional_list)

Traditional Python list created with for loop: [2, 4, 6, 8, 10]


In [ ]:
np.linspace(7,25,10)

array([ 7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.])

In [ ]:
np.random.rand(2,2)

array([[0.91063193, 0.94110053],
       [0.92354186, 0.0506288 ]])

In [ ]:
np.random.randint(1,100, 5)

array([45, 58, 92, 82, 45])

In [ ]:
data= np.array([[1,2], [3,4]])
print(data.ndim)

2


In [ ]:
matriks = np.zeros((3,4))
print(matriks.shape)
print(matriks.size)

(3, 4)
12


In [ ]:
desimal = np.array([1.1, 2.2, 3.3])
print(desimal.dtype)

float64


In [ ]:
arr = np.arange(6)
matrix = arr.reshape(2,3)
print(matrix)

[[0 1 2]
 [3 4 5]]


In [ ]:
lost_biasa=[]

In [ ]:
class Node:
  def __init__(self, data):
    self.left = None
    self.data = data
    self.right = None

In [ ]:
import numpy as np

HistoryStack = np.array([], dtype=str)
RedoStack = np.array([], dtype=str)

def cetak_layar():
    print(f"Kalimat : {' '.join(HistoryStack)}")
    print(f"History : {HistoryStack}")
    print(f"Redo    : {RedoStack}")
    print("----------------------------------------")

def ketik(kata):
    global HistoryStack, RedoStack
    print(f"[Aksi] Ketik: '{kata}'")

    HistoryStack = np.append(HistoryStack, kata)


    RedoStack = np.array([], dtype=str)

    cetak_layar()

def undo():
    global HistoryStack, RedoStack
    print("[Aksi] Undo")

    if len(HistoryStack) > 0:
        data_pop = HistoryStack[-1]
        HistoryStack = HistoryStack[:-1]

        RedoStack = np.append(RedoStack, data_pop)

    cetak_layar()

def redo():
    global HistoryStack, RedoStack
    print("[Aksi] Redo")

    if len(RedoStack) > 0:
        data_pop = RedoStack[-1]
        RedoStack = RedoStack[:-1]

        HistoryStack = np.append(HistoryStack, data_pop)

    cetak_layar()

ketik("Halo")
ketik("Dunia")
undo()
redo()

[Aksi] Ketik: 'Halo'
Kalimat : Halo
History : ['Halo']
Redo    : []
----------------------------------------
[Aksi] Ketik: 'Dunia'
Kalimat : Halo Dunia
History : ['Halo' 'Dunia']
Redo    : []
----------------------------------------
[Aksi] Undo
Kalimat : Halo
History : ['Halo']
Redo    : ['Dunia']
----------------------------------------
[Aksi] Redo
Kalimat : Halo Dunia
History : ['Halo' 'Dunia']
Redo    : []
----------------------------------------


In [ ]:
class textnambahkurang:
    def __init__(self):
        self.history_stack = []  #HistoryStack
        self.redo_stack = []     #RedoStack
        self.current_text = ""

    def ketik(self, teks):
        #Simpan kondisi sebelumnya ke history
        self.history_stack.append(self.current_text)
        #Tambah teks baru
        self.current_text += teks
        #Kosongkan redo stack
        self.redo_stack.clear()
        self.tampilkan()

    def undo(self):
        if self.history_stack:
            #Pindahkan ke redo
            self.redo_stack.append(self.current_text)
            #Ambil dari history
            self.current_text = self.history_stack.pop()
        else:
            print("ga bisa diundo")
        self.tampilkan()

    def redo(self):
        if self.redo_stack:
            #Pindahkan ke history
            self.history_stack.append(self.current_text)
            #Ambil dari redo
            self.current_text = self.redo_stack.pop()
        else:
            print("ga bisa diredo")
        self.tampilkan()

    def tampilkan(self):
        print("pertanyaan:", self.current_text)


# Contoh penggunaan
nana = textnambahkurang()

nana.ketik("nama")
print(nana.history_stack)
print(nana.redo_stack)
nana.ketik("lo")
print(nana.history_stack)
print(nana.redo_stack)
nana.undo()
print(nana.history_stack)
print(nana.redo_stack)
nana.undo()
print(nana.history_stack)
print(nana.redo_stack)
nana.redo()
print(nana.history_stack)
print(nana.redo_stack)
nana.ketik("siapa?")
print(nana.history_stack)
print(nana.redo_stack)
nana.redo()
print(nana.history_stack)
print(nana.redo_stack)  #ini tidak akan jalan karena redo sudah di-reset

pertanyaan: nama
['']
[]
pertanyaan: namalo
['', 'nama']
[]
pertanyaan: nama
['']
['namalo']
pertanyaan: 
[]
['namalo', 'nama']
pertanyaan: nama
['']
['namalo']
pertanyaan: namasiapa?
['', 'nama']
[]
ga bisa diredo
pertanyaan: namasiapa?
['', 'nama']
[]


In [ ]:
import numpy as np

class MesinWaktu:
    def __init__(self):
        self.history_stack = np.array([])
        self.redo_stack = np.array([])

    def _cetak_layar(self):
        print(f"Kalimat : {' '.join(self.history_stack)}")
        print(f"History : {self.history_stack}")
        print(f"Redo    : {self.redo_stack}")
        print("----------------------------------------")

    def ketik(self, kata):
        print(f"[Aksi] Ketik: '{kata}'")
        self.history_stack = np.append(self.history_stack, kata)
        self.redo_stack = np.array([])
        self._cetak_layar()

    def undo(self):
        print("[Aksi] Undo")
        if len(self.history_stack) > 0:
            data_pop = self.history_stack[-1]
            self.history_stack = self.history_stack[:-1]
            self.redo_stack = np.append(self.redo_stack, data_pop)
        self._cetak_layar()

    def redo(self):
        print("[Aksi] Redo")
        if len(self.redo_stack) > 0:
            data_pop = self.redo_stack[-1]
            self.redo_stack = self.redo_stack[:-1]
            self.history_stack = np.append(self.history_stack, data_pop)
        self._cetak_layar()

editor = MesinWaktu()
editor.ketik("Halo")
editor.ketik("Dunia")
editor.undo()
editor.redo()
editor.ketik("Python")
editor.undo()
editor.ketik("Colab")


[Aksi] Ketik: 'Halo'
Kalimat : Halo
History : ['Halo']
Redo    : []
----------------------------------------
[Aksi] Ketik: 'Dunia'
Kalimat : Halo Dunia
History : ['Halo' 'Dunia']
Redo    : []
----------------------------------------
[Aksi] Undo
Kalimat : Halo
History : ['Halo']
Redo    : ['Dunia']
----------------------------------------
[Aksi] Redo
Kalimat : Halo Dunia
History : ['Halo' 'Dunia']
Redo    : []
----------------------------------------
[Aksi] Ketik: 'Python'
Kalimat : Halo Dunia Python
History : ['Halo' 'Dunia' 'Python']
Redo    : []
----------------------------------------
[Aksi] Undo
Kalimat : Halo Dunia
History : ['Halo' 'Dunia']
Redo    : ['Python']
----------------------------------------
[Aksi] Ketik: 'Colab'
Kalimat : Halo Dunia Colab
History : ['Halo' 'Dunia' 'Colab']
Redo    : []
----------------------------------------


In [2]:
matriks = np.random.randint(1, 101, size=(5, 5))

print("array 5x5")
print(matriks)
print("\n")

nilai_mean = np.mean(matriks)
nilai_max = np.max(matriks)
nilai_min = np.min(matriks)

print("Cari Max, Min, Mean")
print(f"Mean (Rata-rata) : {nilai_mean}")
print(f"Max (Tertinggi)  : {nilai_max}")
print(f"Min (Terendah)   : {nilai_min}")
print("\n")

matriks_centered = matriks - nilai_mean

print("Mean Centering")
print(matriks_centered)

array 5x5
[[41 78 46 49 33]
 [28  5 61 51 19]
 [ 8 48  7 82  5]
 [72 64 24 60 73]
 [82 68 28 14 59]]


Cari Max, Min, Mean
Mean (Rata-rata) : 44.2
Max (Tertinggi)  : 82
Min (Terendah)   : 5


Mean Centering
[[ -3.2  33.8   1.8   4.8 -11.2]
 [-16.2 -39.2  16.8   6.8 -25.2]
 [-36.2   3.8 -37.2  37.8 -39.2]
 [ 27.8  19.8 -20.2  15.8  28.8]
 [ 37.8  23.8 -16.2 -30.2  14.8]]


In [30]:
matriks = np.random.randint(1, 101, 25)
matrix = matriks.reshape(5,5)

print(f"""array 5x5
{matrix}\n""")



nilai_mean = np.mean(matriks)
nilai_max = np.max(matriks)
nilai_min = np.min(matriks)

print("Cari Max, Min, Mean")
print(f"""Mean (Rata-rata) : {nilai_mean}
Max (Tertinggi)  : {nilai_max}
Min (Terendah)   : {nilai_min}\n""")


broadcast_array = matrix - nilai_mean

print("Mean Centering")
print(broadcast_array)

array 5x5
[[32 96 43 95 87]
 [ 2 64 89 10  7]
 [28 29 80 28 27]
 [39  4 61 71 43]
 [21 72 58 54 44]]

Cari Max, Min, Mean
Mean (Rata-rata) : 47.36
Max (Tertinggi)  : 96
Min (Terendah)   : 2

Mean Centering
[[-15.36  48.64  -4.36  47.64  39.64]
 [-45.36  16.64  41.64 -37.36 -40.36]
 [-19.36 -18.36  32.64 -19.36 -20.36]
 [ -8.36 -43.36  13.64  23.64  -4.36]
 [-26.36  24.64  10.64   6.64  -3.36]]


In [32]:
import sympy as sp

sp.Rational(1,3)

1/3

In [31]:
pecahan = 1/3
print(pecahan)

0.3333333333333333


In [64]:
sp.init_printing()

x, y, z = sp.symbols('x y z')

x
persamaan = x**2 + 2*x + 1
persamaan


 2          
x  + 2⋅x + 1

In [44]:
sp.pprint(persamaan)

 2          
x  + 2⋅x + 1


In [40]:
y

y

In [42]:
f = x**2 + 2*x + 1
print(f)

x**2 + 2*x + 1


In [51]:
g = (x+1)**2

sp.expand(g)

h = sp.expand(g)

In [53]:
h

 2          
x  + 2⋅x + 1

In [54]:
i = sp.factor(h)

i


       2
(x + 1) 

In [58]:
rumus_trigonometri = sp.sin(x)**2 + sp.cos(x)**2
rumus_trigonometri



   2         2   
sin (x) + cos (x)

In [57]:
rumus_simple = sp.simplify(rumus_trigonometri)

rumus_simple

1

In [60]:
prsmaan_br = x**2 + 3


In [61]:
prsmaan_br.subs(x, 5)

28

In [65]:
anu = (x + z) * y + 5

In [68]:
anu.subs({x:2,y:3,z:4})

23

In [70]:
r = sp.symbols('r')
rms_ling = sp.pi*r**2
rms_ling

   2
π⋅r 

In [71]:
rms_ling.evalf()

                  2
3.14159265358979⋅r 

In [ ]:
np.linspace

In [72]:
sp.Eq(x**2 - 4, 0)

 2        
x  - 4 = 0

In [ ]:
sp.Eq(y, x+1)

In [73]:
sp.solve(sp.Eq(x**2 - 4, 0))

[-2, 2]